# 6502 SBC Emulator - Soundtest ROM configuration

[cpu]
speed_hz = 27000000
debug    = 0         # 1 = start in monitor
model    = 6502      # 6502 (NMOS) or 65c02 (CMOS)

[sram]
base = 0x0000
size = 0x8000

[rom]
base = 0xC000
size = 0x4000
file = roms/soundtest.rom

[via]
base = 0x8800

[uart]
base = 0x8810
mode = stdio
