#!/usr/bin/env python3
"""Convert a siddump raw frame stream into a 6502 player ROM for sound_chip4.

  siddump.exe <file.sid> <seconds> --raw frames.raw
  convert_sid.py frames.raw soundsid.s [delay] [--no-vectors]

The player loops the excerpt forever. Each 50 Hz frame it applies any pending
frequency CHANGES (compressed: only stored when the SID frequency changes, so
held notes cost nothing) so vibrato/slides/arpeggios track, and it fires a note
trigger on each SID gate-on, with the note length set to the gate-high span.
SID filter / pulse-width / ring-mod are dropped. Targets the 16 KB shadow ROM
at $C000 (reliable "G C000" entry).
"""
import sys

PAL_CLK = 985248.0
ATK_MS    = [2,8,16,24,38,56,68,80,100,250,500,800,1000,3000,5000,8000]
DECREL_MS = [6,24,48,72,114,168,204,240,300,750,1500,2400,3000,9000,15000,24000]

def clampb(v): return 0 if v < 0 else 255 if v > 255 else int(v)
def hz_of(s):
    h = round(s * PAL_CLK / 16777216.0)
    return 0 if h < 0 else 65535 if h > 65535 else h
def waveform(c):
    if c & 0x80: return 4
    if c & 0x40: return 1
    if c & 0x20: return 2
    if c & 0x10: return 3
    return 0

def main():
    if len(sys.argv) < 3:
        print("usage: convert_sid.py frames.raw out.s [delay] [--no-vectors]", file=sys.stderr)
        return 2
    raw = open(sys.argv[1], "rb").read()
    out = sys.argv[2]
    rest = sys.argv[3:]
    no_vectors = "--no-vectors" in rest
    nums = [a for a in rest if not a.startswith("--")]
    # delay = total outer loops (DELAY_HI*DELAY_MID); larger = slower playback.
    delay_total = int(nums[0]) if nums else 2400
    dmid = 200
    dhi = max(1, min(255, round(delay_total / dmid)))

    nf = len(raw) // 15
    freq = [[0]*nf for _ in range(3)]
    ctrl = [[0]*nf for _ in range(3)]
    ad   = [[0]*nf for _ in range(3)]
    sr   = [[0]*nf for _ in range(3)]
    for f in range(nf):
        for v in range(3):
            b = raw[f*15 + v*5 : f*15 + v*5 + 5]
            freq[v][f] = hz_of(b[0] | (b[1] << 8))
            ctrl[v][f] = b[2]; ad[v][f] = b[3]; sr[v][f] = b[4]

    # per-voice frequency-change list: frame_lo,frame_hi,freq_lo,freq_hi
    chg = []
    for v in range(3):
        s = []; prev = -1
        for f in range(nf):
            h = freq[v][f]
            if h != prev:
                s += [f & 0xFF, (f >> 8) & 0xFF, h & 0xFF, (h >> 8) & 0xFF]
                prev = h
        s += [0xFF, 0xFF, 0, 0]   # terminator (frame hi = $FF)
        chg.append(s)

    # note-on events (gate 0->1 spans)
    events = []
    for v in range(3):
        prev_gate = 0; f = 0
        while f < nf:
            gate = ctrl[v][f] & 1
            if gate and not prev_gate:
                e = f + 1
                while e < nf and (ctrl[v][e] & 1):
                    e += 1
                dur_ms = min(65535, (e - f) * 20)
                a = ad[v][f] >> 4; d = ad[v][f] & 15
                ss = sr[v][f] >> 4; r = sr[v][f] & 15
                events.append((f, v, waveform(ctrl[v][f]),
                               clampb(ATK_MS[a] // 8), clampb(DECREL_MS[d] // 8),
                               clampb(ss * 17), clampb(DECREL_MS[r] // 8), dur_ms))
            prev_gate = gate; f += 1
    events.sort(key=lambda e: e[0])
    estream = []
    for (f, v, w, a, d, s, r, dur) in events:
        estream += [f & 0xFF, (f>>8)&0xFF, v, w, a, d, s, r, dur & 0xFF, (dur>>8)&0xFF]
    estream += [0xFF, 0xFF, 0,0,0,0,0,0,0,0]

    def bytes_dir(label, data):
        out = [f"{label}:"]
        for i in range(0, len(data), 16):
            out.append("    .byte " + ",".join(str(x) for x in data[i:i+16]))
        return "\n".join(out)

    total = len(chg[0]) + len(chg[1]) + len(chg[2]) + len(estream)
    with open(out, "w") as fp:
        fp.write(PLAYER.format(nframes=nf, delay=delay_outer))
        fp.write("\n.segment \"RODATA\"\n\n")
        fp.write(bytes_dir("chg0", chg[0]) + "\n")
        fp.write(bytes_dir("chg1", chg[1]) + "\n")
        fp.write(bytes_dir("chg2", chg[2]) + "\n")
        fp.write(bytes_dir("events", estream) + "\n")
        if not no_vectors:
            fp.write("\n.segment \"VECTORS\"\n    .word reset\n    .word reset\n    .word reset\n")
    print(f"frames={nf} ({nf/50:.1f}s)  events={len(events)}  "
          f"freq-chg={sum(len(c) for c in chg)}B  events={len(estream)}B  "
          f"data~{total}B -> {out}")

PLAYER = r"""; soundsid.s - GENERATED by tools/sid_convert/convert_sid.py  (do not edit)
; Plays a converted SID excerpt on sound_chip4: compressed live-frequency
; changes + per-note triggers, looped forever.

V0 = $8830
V1 = $8890
V2 = $889A

cp0 = $10
cp1 = $12
cp2 = $14
ep  = $16
fr  = $18
vb  = $1A

NFRAMES   = {nframes}
DELAY_HI  = {dhi}
DELAY_MID = {dmid}

.segment "CODE"

reset:
    sei
    cld
    ldx #$FF
    txs
restart:
    lda #<chg0
    sta cp0
    lda #>chg0
    sta cp0+1
    lda #<chg1
    sta cp1
    lda #>chg1
    sta cp1+1
    lda #<chg2
    sta cp2
    lda #>chg2
    sta cp2+1
    lda #<events
    sta ep
    lda #>events
    sta ep+1
    lda #0
    sta fr
    sta fr+1

frame_loop:
    ; voice 0 frequency changes due this frame
@f0:
    ldy #1
    lda (cp0),y
    cmp #$FF
    beq @f0d
    cmp fr+1
    bne @f0d
    dey
    lda (cp0),y
    cmp fr
    bne @f0d
    ldy #2
    lda (cp0),y
    sta V0+0
    ldy #3
    lda (cp0),y
    sta V0+1
    ldx #cp0
    jsr adv4
    jmp @f0
@f0d:
    ; voice 1
@f1:
    ldy #1
    lda (cp1),y
    cmp #$FF
    beq @f1d
    cmp fr+1
    bne @f1d
    dey
    lda (cp1),y
    cmp fr
    bne @f1d
    ldy #2
    lda (cp1),y
    sta V1+0
    ldy #3
    lda (cp1),y
    sta V1+1
    ldx #cp1
    jsr adv4
    jmp @f1
@f1d:
    ; voice 2
@f2:
    ldy #1
    lda (cp2),y
    cmp #$FF
    beq @f2d
    cmp fr+1
    bne @f2d
    dey
    lda (cp2),y
    cmp fr
    bne @f2d
    ldy #2
    lda (cp2),y
    sta V2+0
    ldy #3
    lda (cp2),y
    sta V2+1
    ldx #cp2
    jsr adv4
    jmp @f2
@f2d:

    ; note-on events for this frame
ev_loop:
    ldy #1
    lda (ep),y
    cmp #$FF
    beq ev_done
    cmp fr+1
    bne ev_done
    dey
    lda (ep),y
    cmp fr
    bne ev_done
    jsr apply_event
    jmp ev_loop
ev_done:

    inc fr
    bne @nf
    inc fr+1
@nf:
    lda fr+1
    cmp #>NFRAMES
    bne @cont
    lda fr
    cmp #<NFRAMES
    bne @cont
    jmp restart
@cont:
    jsr delay
    jmp frame_loop

; add 4 to the ZP pointer whose low byte is at $00,X
adv4:
    clc
    lda $00,x
    adc #4
    sta $00,x
    bcc @d
    inc $01,x
@d:
    rts

apply_event:
    ldy #2
    lda (ep),y
    tax
    lda vbl,x
    sta vb
    lda vbh,x
    sta vb+1
    ldy #8
    lda (ep),y
    ldy #2
    sta (vb),y
    ldy #9
    lda (ep),y
    ldy #3
    sta (vb),y
    lda #200
    ldy #4
    sta (vb),y
    ldy #4
    lda (ep),y
    ldy #6
    sta (vb),y
    ldy #5
    lda (ep),y
    ldy #7
    sta (vb),y
    ldy #6
    lda (ep),y
    ldy #8
    sta (vb),y
    ldy #7
    lda (ep),y
    ldy #9
    sta (vb),y
    ldy #3
    lda (ep),y
    asl
    asl
    asl
    asl
    ora #$01
    ldy #5
    sta (vb),y
    clc
    lda ep
    adc #10
    sta ep
    bcc @d
    inc ep+1
@d:
    rts

; 3-level busy-wait paces the frame rate: DELAY_HI x DELAY_MID x 256 iterations.
; Tune via the convert_sid.py delay argument (larger = slower).
delay:
    ldx #DELAY_HI
@o:
    lda #DELAY_MID
@m:
    ldy #0
@i:
    dey
    bne @i
    sec
    sbc #1
    bne @m
    dex
    bne @o
    rts

vbl: .byte <V0, <V1, <V2
vbh: .byte >V0, >V1, >V2
"""

if __name__ == "__main__":
    sys.exit(main() or 0)
